### PR TITLE
grpc request type and views

### PR DESCRIPTION
**Pull request by mirzakhany**
This Pr is preparing grpc request view as part of #44

### CODE REVIEW

**Comment by mirzakhany** [comment]
Current state: 

Screenshot 2024-05-26 at 21 03 48

**Comment by mirzakhany** [comment]
Current State: (29 May) 
Screenshot 2024-05-29 at 22 41 38

**Comment by mirzakhany** [comment]
Current state: some of request views are in place and I will continue to make first grpc call implementation.
( 30 may) 

Screenshot 2024-05-30 at 22 16 20
Screenshot 2024-05-30 at 22 16 29

**Comment by mirzakhany** [comment]
Last update on this ( 25 Jun), loading methods by server reflection and protocol file is working fine. as well as loading the request example and performing a basic grpc call. 

Screenshot 2024-06-25 at 23 25 17

**Comment by ccoVeille** [comment]
Wow 🥳

**Pull request merged**
